spring.application.name=vibe-java

spring.datasource.url=jdbc:postgresql://localhost:5432/vibe_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# PENTING: Gunakan 'validate', karena DDL akan di-handle oleh Liquibase sepenuhnya.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# Contoh Konfigurasi Custom untuk Configuration Properties dan Feign Client
app.api.key=random-secret-key-development
app.external-service.base-url=https://api.public-service.com
